---
title: "DNA Training Slide Decks"
subtitle: ""
format:
  html:
    theme: [obis_theme.scss]
    css: [custom.css]
---

## Trainings delivered

- [2026 July INVEMAR DNA data management](index-invemar.qmd)
- [2026 July OBIS Node Training on DNA data](https://iobis.github.io/obis_edna_slides_node_training/)

## Slide Decks

- [What is Environmental DNA](https://github.com/iobis/obis_edna_slides/blob/invemar-training/slides/pdf_slides/1-introduction-edna.pdf){target="_blank" rel="noopener noreferrer"}?
    - Introduction to eDNA methods and what we can do with it
- [What information is important at each step of an eDNA workflow?](https://github.com/iobis/obis_edna_slides/blob/invemar-training/slides/pdf_slides/2-information-at-each-step-edna-workflow.pdf){target="_blank" rel="noopener noreferrer"}
    - Overview of the information that should be captured when managing DNA datasets
- [Darwin Core and DNA-Derived Data](index-dna-extension.qmd)
    - Overview of DNA data types and how DNA data fits into Darwin Core
- [eDNA Data Management History](https://youtu.be/zsH8KIis_yA){target="_blank" rel="noopener noreferrer"} (YouTube recording)
- [Mapping molecular data to Darwin Core](index-map-edna-to-dwc.html) 
  - How to record the important data and metadata in Darwin Core and the DNA-derived extension
- [eDNA Quality Control](https://github.com/iobis/obis_edna_slides/blob/invemar-training/slides/pdf_slides/3_edna_qc_molecular.pdf){target="_blank" rel="noopener noreferrer"}
    - Overview of quality control steps in an eDNA workflow
- [Ongoing data standardisation intitiatives (OBON)](https://www.youtube.com/playlist?list=PLS6jqgZoUzto) (YouTube recording)
