---
title: "OBIS Training Slides"
subtitle: "Pick a deck to open it as a full-screen presentation"
format:
  html:
    theme: [obis_theme.scss]
    css: [custom.css]
---

## Introduction to DNA Data Management Slide Decks

1. [What is Environmental DNA](https://github.com/iobis/obis_edna_slides/blob/invemar-training/slides/pdf_slides/1-introduction-edna.pdf){target="_blank" rel="noopener noreferrer"}?
    - Introduction to eDNA methods and what we can do with it
2. [What information is important at each step of an eDNA workflow?](https://github.com/iobis/obis_edna_slides/blob/invemar-training/slides/pdf_slides/2-information-at-each-step-edna-workflow.pdf){target="_blank" rel="noopener noreferrer"}
    - Overview of the information that should be captured when managing DNA datasets
3. [FAIR Data & Biodiversity Standards](index-fair-data.qmd)
    - Background information on what FAIR data is and a brief overview of Darwin Core and Essential Ocean Variables
4. [Darwin Core and DNA-Derived Data](index-dna-extension.qmd)
    - Details on how to fit the types of DNA data into Darwin Core, and how to map the important information (Slide Deck 2) to DwC terms
5. [eDNA Data Management History](https://youtu.be/zsH8KIis_yA){target="_blank" rel="noopener noreferrer"} (YouTube recording)
6. [Mapping Molecular data to Darwin Core](index-map-edna-to-dwc.html)
7. Quality Control
    - eDNA Quality Control
    - [Taxonomy quality control tool demo](https://www.youtube.com/watch?v=e7HBAFf5NFg&feature=youtu.be){target="_blank" rel="noopener noreferrer"} (YouTube recording)
    - [OBIS Quality Control](index-qc.qmd)
        - Overview of quality control checks you should do with any OBIS dataset, DNA or otherwise
8. [Ongoing data standardisation intitiatives (OBON)](https://www.youtube.com/playlist?list=PLS6jqgZoUzto) (YouTube recording)
9. [Publishing & IPT](index-publishing.qmd)
    - How to publish data using the Integrated Publishing Toolkit (IPT) software
10. [Accessing OBIS (DNA) Data](index-access.qmd)
    - How to access data from OBIS, including DNA data

## Other decks

- [Publishing eDNA Data in OBIS (full deck)](index-edna-full.qmd)
