#!/usr/bin/env Rscript

# Refresh the cached OBIS statistics that the slides display.
#
#   Rscript scripts/fetch-obis-stats.R           fetch and rewrite the cache
#   Rscript scripts/fetch-obis-stats.R --check   report what would change, write nothing
#
# This is deliberately NOT part of the render. Nothing in _quarto.yml calls it,
# and `quarto render` never reaches the network: the slides read the committed
# _variables.yml through {{< var >}}, which is plain text substitution. Adding a
# pre-render hook to _quarto.yml would break that guarantee.
#
# Refreshing is a decision, and it shows up as a reviewable diff in git.

suppressPackageStartupMessages({
  library(httr2)
  library(yaml)
})

STATS_URL <- "https://api.obis.org/statistics"
NODE_URL  <- "https://api.obis.org/node"
OUT       <- "_variables.yml"

# The Secretariat coordinates OBIS rather than publishing to it, so it does not
# count as a node. Matched on id: node names get edited, ids do not.
SECRETARIAT_ID <- "310922b4-9d0c-4de1-92d7-9b442d34765b"

check_only <- "--check" %in% commandArgs(trailingOnly = TRUE)

die <- function(...) {
  message("fetch-obis-stats: ", ...)
  message("Nothing written; ", OUT, " left as it was.")
  quit(status = 1)
}

get_json <- function(url) {
  resp <- tryCatch(
    request(url) |>
      req_user_agent("obis_edna_slides stats refresh") |>
      req_timeout(30) |>
      req_perform(),
    error = function(e) die("could not reach ", url, " (", conditionMessage(e), ")")
  )
  resp_body_json(resp, simplifyVector = TRUE)
}

# A stat that came back missing, non-numeric or nonsensical means the API
# changed shape. Better to stop than to quietly publish a wrong number.
need_count <- function(x, field) {
  if (is.null(x[[field]])) die("'", field, "' missing from the API response")
  v <- suppressWarnings(as.numeric(x[[field]]))
  if (is.na(v) || v <= 0) die("'", field, "' is not a positive number: ", x[[field]])
  v
}

comma <- function(x) formatC(x, format = "d", big.mark = ",")

# Big totals read better spoken than digit by digit: 229,141,362 -> "229.1 million".
short <- function(x) {
  trim <- function(v) sub("\\.0$", "", formatC(v, format = "f", digits = 1))
  if (x >= 1e9)      paste(trim(x / 1e9), "billion")
  else if (x >= 1e6) paste(trim(x / 1e6), "million")
  else               comma(x)
}

stats <- get_json(STATS_URL)
nodes <- get_json(NODE_URL)

records      <- need_count(stats, "records")
species      <- need_count(stats, "species")
taxa         <- need_count(stats, "taxa")
datasets     <- need_count(stats, "datasets")
specieslevel <- need_count(stats, "specieslevel")

years <- stats$yearrange
if (length(years) != 2 || anyNA(suppressWarnings(as.integer(years)))) {
  die("'yearrange' is not a pair of years: ", paste(years, collapse = ", "))
}
years <- as.integer(years)

if (is.null(nodes$results) || !"id" %in% names(nodes$results)) {
  die("the node list came back without an 'id' column")
}
if (!SECRETARIAT_ID %in% nodes$results$id) {
  die("the Secretariat id ", SECRETARIAT_ID, " is no longer in the node list. ",
      "Check https://api.obis.org/node and update SECRETARIAT_ID before rerunning.")
}
node_count <- nrow(nodes$results) - 1L

now <- Sys.time()
attr(now, "tzone") <- "UTC"

# Emitted by hand rather than via as.yaml so that key order, integer formatting
# and quoting stay stable, which keeps the git diff between refreshes readable.
vals <- list(
  retrieved            = format(now, "%Y-%m-%d"),
  retrieved_utc        = format(now, "%Y-%m-%dT%H:%M:%SZ"),
  source_statistics    = STATS_URL,
  source_nodes         = NODE_URL,
  records              = records,
  records_fmt          = comma(records),
  records_short        = short(records),
  specieslevel         = specieslevel,
  specieslevel_fmt     = comma(specieslevel),
  specieslevel_short   = short(specieslevel),
  species              = species,
  species_fmt          = comma(species),
  taxa                 = taxa,
  taxa_fmt             = comma(taxa),
  datasets             = datasets,
  datasets_fmt         = comma(datasets),
  nodes                = node_count,
  nodes_fmt            = comma(node_count),
  year_min             = years[1],
  year_max             = years[2]
)

emit <- function(v) if (is.numeric(v)) formatC(v, format = "d") else paste0('"', v, '"')

lines <- c(
  paste0("# Generated by scripts/fetch-obis-stats.R on ", vals$retrieved, ". Do not edit by hand."),
  "# Refresh with: Rscript scripts/fetch-obis-stats.R",
  "",
  "obis:",
  vapply(names(vals), function(k) sprintf("  %s: %s", k, emit(vals[[k]])), character(1)),
  ""
)

previous <- if (file.exists(OUT)) read_yaml(OUT)$obis else NULL

changed <- Filter(Negate(is.null), lapply(names(vals), function(k) {
  if (grepl("^retrieved", k)) return(NULL)          # always moves; not news
  old <- previous[[k]]
  if (is.null(old)) return(sprintf("  %-20s -> %s (new)", k, vals[[k]]))
  if (as.character(old) != as.character(vals[[k]]))
    sprintf("  %-20s %s -> %s", k, old, vals[[k]])
  else NULL
}))

if (length(changed) == 0 && !is.null(previous)) {
  message("No change since ", previous$retrieved, ".")
} else {
  message(if (is.null(previous)) "New cache:" else "Changes:")
  message(paste(unlist(changed), collapse = "\n"))
}

if (check_only) {
  message("\n--check: nothing written.")
  quit(status = 0)
}

# Write to a temp file in the same directory and move it into place, so an
# interrupted run cannot leave a half-written cache behind.
tmp <- tempfile("obis-stats-", tmpdir = dirname(normalizePath(OUT, mustWork = FALSE)))
writeLines(lines, tmp)
if (!file.rename(tmp, OUT)) {
  unlink(tmp)
  die("could not move the new cache into place at ", OUT)
}

message("\nWrote ", OUT, " (retrieved ", vals$retrieved_utc, ").")
